pub(crate) mod collect;
pub(crate) mod creation;
pub(crate) mod friends;
pub(crate) mod lyrics;
pub(crate) mod score;
pub(crate) mod setting;
pub(crate) mod song;
pub(crate) mod song_type;
pub(crate) mod user;
