//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod prelude;

pub mod collect;
pub mod creation;
pub mod friends;
pub mod lyric;
pub mod score;
pub mod setting;
pub mod song;
pub mod song_type;
pub mod user;
