//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::collect::Entity as Collect;
pub use super::creation::Entity as Creation;
pub use super::friends::Entity as Friends;
pub use super::lyric::Entity as Lyric;
pub use super::score::Entity as Score;
pub use super::setting::Entity as Setting;
pub use super::song::Entity as Song;
pub use super::song_type::Entity as SongType;
pub use super::user::Entity as User;
